### ISSUE TITLE
group- does emit code when the body is not emitted

### ISSUE THREAD

**Issue by keerts** [adzerk-oss/cljs-console#1]
```
(log/group- "event processed '(name (first event-v)) ('(count event-q)))"
               (log/debug "~{event-v} events remaining: #(count event-q)"))
```

When compiled for level warn, the group- message is in the compiled code when it should not.

**Comment by mitchelkuijpers** [comment]
this code:

```
(log/group- "foo"
            (log/info "bar")
            (log/info "bar"))
```

works if I paste it in the cljs-repl but if i put it in a file and then run cljsbuild I get a:

```
WARNING: Use of undeclared Var clojure.tools.logging/log* at line 170 /Users/mitkuijp/Development/relations_for_jira/src/cljs/relations_for_jira/form_builder/handlers.cljs
clojure.lang.ExceptionInfo: failed compiling file:/Users/mitkuijp/Development/relations_for_jira/src/cljs/relations_for_jira/form_builder/handlers.cljs {:file #object[java.io.File 0x17f54064 "/Users/mitkuijp/Development/relations_for_jira/src/cljs/relations_for_jira/form_builder/handlers.cljs"]}
    at clojure.core$ex_info.invoke(core.clj:4593)
    at cljs.compiler$compile_file$fn__28261.invoke(compiler.cljc:1369)
    at cljs.compiler$compile_file.invoke(compiler.cljc:1336)
    at cljs.closure$compile_file.invoke(closure.clj:437)
    at cljs.closure$eval30026$fn__30027.invoke(closure.clj:504)
    at cljs.closure$eval29962$fn__29963$G__29951__29970.invoke(closure.clj:394)
    at cljs.closure$eval30032$fn__30033.invoke(closure.clj:513)
    at cljs.closure$eval29962$fn__29963$G__29951__29970.invoke(closure.clj:394)
    at cljs.closure$compile_sources$iter__30146__30150$fn__30151.invoke(closure.clj:827)
    at clojure.lang.LazySeq.sval(LazySeq.java:40)
    at clojure.lang.LazySeq.seq(LazySeq.java:49)
    at clojure.lang.Cons.next(Cons.java:39)
    at clojure.lang.RT.next(RT.java:674)
    at clojure.core$next__4112.invoke(core.clj:64)
    at clojure.core$dorun.invoke(core.clj:3010)
    at clojure.core$doall.invoke(core.clj:3025)
    at cljs.closure$compile_sources.invoke(closure.clj:823)
    at cljs.closure$build.invoke(closure.clj:1895)
    at cljs.closure$watch$buildf__30544.invoke(closure.clj:1977)
    at cljs.closure$watch.invoke(closure.clj:2026)
    at cljs.build.api$watch.invoke(api.clj:220)
    at cljs.build.api$watch.invoke(api.clj:217)
    at cljs.build.api$watch.invoke(api.clj:212)
    at user$eval34929.invoke(form-init3623894741710962767.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6782)
    at clojure.lang.Compiler.eval(Compiler.java:6772)
    at clojure.lang.Compiler.load(Compiler.java:7227)
    at clojure.lang.Compiler.loadFile(Compiler.java:7165)
    at clojure.main$load_script.invoke(main.clj:275)
    at clojure.main$init_opt.invoke(main.clj:280)
    at clojure.main$initialize.invoke(main.clj:308)
    at clojure.main$null_opt.invoke(main.clj:343)
    at clojure.main$main.doInvoke(main.clj:421)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: No method in multimethod 'emit-constant' for dispatch value: class clojure.lang.Namespace
    at clojure.lang.MultiFn.getFn(MultiFn.java:156)
    at clojure.lang.MultiFn.invoke(MultiFn.java:229)
    at cljs.compiler$eval27782$fn__27784.invoke(compiler.cljc:419)
    at clojure.lang.MultiFn.invoke(MultiFn.java:229)
    at cljs.compiler$emit.invoke(compiler.cljc:170)
    at cljs.compiler$emits.doInvoke(compiler.cljc:176)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:630)
    at cljs.compiler$emits.doInvoke(compiler.cljc:177)
    at clojure.lang.RestFn.invoke(RestFn.java:457)
    at cljs.compiler$eval28067$fn__28069.invoke(compiler.cljc:1011)
    at clojure.lang.MultiFn.invoke(MultiFn.java:229)
    at cljs.compiler$emit.invoke(compiler.cljc:170)
    at cljs.compiler$emits.doInvoke(compiler.cljc:176)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:630)
    at cljs.compiler$emitln.doInvoke(compiler.cljc:187)
    at clojure.lang.RestFn.invoke(RestFn.java:436)
    at cljs.compiler$emit_let$fn__28023.invoke(compiler.cljc:878)
    at cljs.compiler$emit_let.invoke(compiler.cljc:866)
    at cljs.compiler$eval28034$fn__28035.invoke(compiler.cljc:887)
    at clojure.lang.MultiFn.invoke(MultiFn.java:229)
    at cljs.compiler$emit.invoke(compiler.cljc:170)
    at cljs.compiler$emits.doInvoke(compiler.cljc:176)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:630)
    at cljs.compiler$emitln.doInvoke(compiler.cljc:187)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at cljs.compiler$eval27998$fn__28000.invoke(compiler.cljc:841)
    at clojure.lang.MultiFn.invoke(MultiFn.java:229)
    at cljs.compiler$emit.invoke(compiler.cljc:170)
    at cljs.compiler$eval27998$fn__28000.invoke(compiler.cljc:842)
    at clojure.lang.MultiFn.invoke(MultiFn.java:229)
    at cljs.compiler$emit.invoke(compiler.cljc:170)
    at cljs.compiler$emits.doInvoke(compiler.cljc:176)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at cljs.compiler$emit_fn_method.invoke(compiler.cljc:691)
    at cljs.compiler$eval27957$fn__27959.invoke(compiler.cljc:776)
    at clojure.lang.MultiFn.invoke(MultiFn.java:229)
    at cljs.compiler$emit.invoke(compiler.cljc:170)
    at cljs.compiler$emits.doInvoke(compiler.cljc:176)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at cljs.compiler$eval27892$fn__27894.invoke(compiler.cljc:616)
    at clojure.lang.MultiFn.invoke(MultiFn.java:229)
    at cljs.compiler$emit.invoke(compiler.cljc:170)
    at cljs.compiler$emit_source.invoke(compiler.cljc:1238)
    at cljs.compiler$compile_file_STAR_$fn__28238.invoke(compiler.cljc:1288)
    at cljs.compiler$with_core_cljs.invoke(compiler.cljc:1152)
    at cljs.compiler$compile_file_STAR_.invoke(compiler.cljc:1277)
    at cljs.compiler$compile_file$fn__28261.invoke(compiler.cljc:1357)
    ... 36 more
```

**Comment by agzam** [comment]
yup, also spy->> and spy-> seemed to be broken ;(
